spring.application.name=AutoLocCCE
server.port=9090
# ── Datasource MySQL ──────────────────
#URL de connexion à la BDD MySQL :
spring.datasource.url=jdbc:mysql://localhost:3306/ProjetSpring?createDatabaseIfNotExist=true
#Nom d'utilisateur MySQL
spring.datasource.username=root
#Mot de passe MySQL
spring.datasource.password=

# ── JPA / Hibernate ──────────────────
#Affiche les requêtes SQL générées en console
spring.jpa.show-sql=true
#Stratégie de génération des tables : update
spring.jpa.hibernate.ddl-auto=update